apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler
  namespace: default
  labels:
    name: multischeduler-example
    schedulingStrategy: meetup
    serviceName: annotation-second-scheduler
    endDevice: '10.20.12.83' 
spec:
  schedulerName: my-scheduler
  containers:
  - name: pod-with-second-annotation-container
    image: k8s.gcr.io/pause:2.0
